### ISSUE TITLE
Denali tooltip style selector easily collides with other tooltip libraries

### ISSUE THREAD

**Issue by jkusa** [denali-design/denali-css#110]
Many tooltip libraries have the word `tooltip` in their class names (ex: `ember-tooltip-base`). Denali tooltip styles look for any class name with the word `tooltip` in it and easily conflicts with other styles. 

One way to work around the issue is to change the selector from `[class*=tooltip]` to `.has-tooltip`.

**Comment by chasturansky** [comment]
Fixed in v2.2.0
