### ISSUE TITLE
Alert: Block level spacing

### ISSUE THREAD

**Issue by chasturansky** [denali-design/denali-css#122]
**Describe the bug**
When I remove the header there is a padding on the p tag

**To Reproduce**
1. For padding on p tag just remove the h5 from the alert

**Expected behavior**
1. Remove top padding from p tag. Add the padding to the h5 to represent the same space.

**Comment by kongriley** [comment]
I'm interested in working on this issue for HackTogether.

**Comment by kongriley** [comment]
PR: https://github.com/denali-design/denali-css/pull/152
