### ISSUE TITLE
Selects: Width is not correct

### ISSUE THREAD

**Issue by chasturansky** [denali-design/denali-css#128]
**Describe the bug**
It seems like the select field is not the default 250px width as the other fields are.

**To Reproduce**
1. Go to https://denali-design.github.io/denali-css/docs/#selects
2. See the first example

**Expected behavior**
Width should be 250px

**Screenshots**
<img width="422" alt="Screen Shot 2021-02-01 at 1 37 35 PM" src="https://user-images.githubusercontent.com/15337851/106634189-6315a600-6534-11eb-818b-3b40dd0915b3.png">

**Additional context**
The width on `.input` element seems to be set to 100px when it should be 250px. Double-check this is not because of the theme.

**Comment by raziyamajeeth** [comment]
Select input is already 250px.
![image](https://user-images.githubusercontent.com/80556695/112792792-bb26df80-9081-11eb-915f-be7ae102f598.png)

**Comment by chasturansky** [comment]
Looks like this was fixed in an update. Thank you for pointing this out.
