### ISSUE TITLE
Sidebar: item can not be disabled

### ISSUE THREAD

**Issue by chasturansky** [denali-design/denali-css#139]
**Describe the bug**
In the sidebar component when you apply `is-disabled` the visual style does not appear and style has a hovered state.

**To Reproduce**
1. Add `is-disabled` to the `<li>` within the primary vertical tabs component.
2. You can see an example when you hover over Tab 5 on [this page](https://denali-design.github.io/denali-css/?path=/story/components-sidebar--default).

**Expected behavior**
The visual appearance should be a grey color and no border color. See the image below.
<img width="424" alt="Screen Shot 2021-03-18 at 7 21 51 PM" src="https://user-images.githubusercontent.com/15337851/111722511-389b5600-881f-11eb-8c66-8125c68de34a.png">

**Comment by kongriley** [comment]
I'm interested in working on this issue for HackTogether.

**Comment by kongriley** [comment]
https://github.com/denali-design/denali-css/pull/153
