### ISSUE TITLE
Multiple README links are broken

### ISSUE THREAD

**Issue by oyving** [denali-design/denali-css#148]
**Describe the bug**
Two links in your README.md do not point to what they're supposed to.
* *getting started page* link is 404.
* *quick start* link send you to `localhost:6006`

**Comment by chasturansky** [comment]
Thank you for the issue. These should now be resolved with the [latest commit](https://github.com/denali-design/denali-css/commit/475223e5d5741c12cd7fbd62d084cfab7d6d232e)
