### ISSUE TITLE
Breadcrumb: Active State

### ISSUE THREAD

**Issue by chasturansky** [denali-design/denali-css#150]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently there is no active state for a breadcrumb.

**Describe alternatives you've considered**
This could be applied through modifiers `is-bold` and `is-grey-800`, but ideally offering a `is-active` to the element.

**Additional context**
<img width="570" alt="Screen Shot 2021-03-18 at 7 54 45 PM" src="https://user-images.githubusercontent.com/15337851/111725163-cbd68a80-8823-11eb-877e-4d44746c4c26.png">

**Comment by raziyamajeeth** [comment]
Interested.

**Comment by chasturansky** [comment]
Feel free to send over a PR and ask questions here!

**Comment by raziyamajeeth** [comment]
https://github.com/denali-design/denali-css/pull/158

**Comment by raziyamajeeth** [comment]
New PR - #160
