### ISSUE TITLE
Fields: does not support front and back icon at the same time

### ISSUE THREAD

**Issue by chasturansky** [denali-design/denali-css#151]
**Describe the bug**
When an icon is added to the front and back the fields do not preform correctly.

**To Reproduce**
1. Link Denali CSS
2. Insert this code
```
<div class="input has-icon-front has-icon-back">
     <span class="d-icon d-filter-horizontal is-brand-300"></span>
     <input type="text" placeholder="Input" />
     <a class="d-icon d-close-circle-solid is-secondary is-sub"></a>
</div>
```

**Expected behavior**
Input should be 250px width and icons should be inline.

**Screenshots**
<img width="336" alt="Screen Shot 2021-03-18 at 8 05 09 PM" src="https://user-images.githubusercontent.com/15337851/111725983-45bb4380-8825-11eb-9fb2-de5ebf71a2d3.png">

**Comment by raziyamajeeth** [comment]
Interested.

**Comment by raziyamajeeth** [comment]
PR - #164
