### ISSUE TITLE
Everything bounces in

### ISSUE THREAD

**Issue by clayreimann** [denali-design/denali-css#35]
If you try and use either of the examples linked on the [resources page](https://denali.design/resource-downloads) all the elements bounce in.

![2019-10-14 16 04 07](https://user-images.githubusercontent.com/930039/66779544-7ebaf000-ee9c-11e9-994d-20041d829181.gif)

**Comment by chasturansky** [comment]
Looked into this slightly and found we have a transition effect on many of our components which is causing the bounce effect.

This is primarily used to create smooth transitions from standard to hover states. We are going to look into how we can keep the smooth state changes while removing the bounce effect.

**Comment by chasturansky** [comment]
The just-released CSS v1.0.3 should address the problem for the template page. Closing issue.
