### ISSUE TITLE
Select options not visible in dark theme

### ISSUE THREAD

**Issue by ope-nz** [denali-design/denali-css#46]
As per description options in a select component are not visible when the dark theme is used.

See image below;

![image](https://user-images.githubusercontent.com/26259049/72226800-f0205100-35f9-11ea-8d32-723312e73faa.png)

**Comment by chasturansky** [comment]
Hi, Thank you for finding this. Could you please provide the browser and confirm this is not a third party JS library for the select?

**Comment by ope-nz** [comment]
I have checked on Chrome, Firefox and Edge. Same behaviour on all.

Easiest way to see it is go to the component demo page and change to Dark mode.
https://denali-design.github.io/denali-css/docs/#dropdown

![image](https://user-images.githubusercontent.com/26259049/72471800-379c1c80-3848-11ea-8e0e-7c1b983f575c.png)

**Comment by chasturansky** [comment]
Added style to options element. This fix is for Firefox and later versions of Chrome. Fix coming out in the next release.
