### ISSUE TITLE
Tabs items without `href` attribute do not have a `cursor: pointer` 

### ISSUE THREAD

**Issue by jkusa** [denali-design/denali-css#51]
Currently, the tab item component is backed by an `<a>` tag. If an `<a>` does not have an `href` attribute, it will not have a `cursor: pointer`. Since not all tab items will be links with `href`s, denali should make all interactive items have a `cursor: pointer`.

**Comment by chasturansky** [comment]
You can switch the `a` tag out for a span class.

**Comment by chasturansky** [comment]
Added this to <li> and .link class. In beta now.
