### ISSUE TITLE
Component example box heights are all over the place in Firefox and Safari

### ISSUE THREAD

**Issue by jazminorozco** [denali-design/denali-css#57]
Almost each component page has issues where the component example box is either too small to see anything at all or cutting off the component some way in safari and firefox

![Screen Shot 2020-04-19 at 2 46 40 PM](https://user-images.githubusercontent.com/20936130/79700937-03246c00-824e-11ea-99cb-383f38067d93.png)

![Screen Shot 2020-04-19 at 2 46 07 PM](https://user-images.githubusercontent.com/20936130/79700940-0b7ca700-824e-11ea-8cad-d70b19170b26.png)

**Comment by chasturansky** [comment]
Can't replicate in Safari. We are relying on javascript to resize these. It looks like firefox is getting stuck on a function.
