### ISSUE TITLE
Chips are stacked in Safari and Firefox

### ISSUE THREAD

**Issue by jazminorozco** [denali-design/denali-css#58]
Chips appear stacked on top of each other in the example box in Safari and Firefox

![Screen Shot 2020-04-19 at 2 42 02 PM](https://user-images.githubusercontent.com/20936130/79700982-54346000-824e-11ea-917c-c50c538eb594.png)

**Comment by chasturansky** [comment]
This is displayed correctly. I can add another space in between each item.
