### ISSUE TITLE
Icon is off center in fields with icon example (Safari, Firefox, Chrome)

### ISSUE THREAD

**Issue by jazminorozco** [denali-design/denali-css#59]
![Screen Shot 2020-04-19 at 2 41 43 PM](https://user-images.githubusercontent.com/20936130/79701004-880f8580-824e-11ea-8d20-a2286aa0532d.png)

**Comment by chasturansky** [comment]
Can't replicate this in version 2. Please confirm this is version 2 and not version 1.0.3

**Comment by chasturansky** [comment]
This has something to do with the iframe, not the actual code.

**Comment by chasturansky** [comment]
We'll be updating the way we do our documentation.
