### ISSUE TITLE
Toggles aren't all clickable in toggles page (Safari, Firefox, Chrome)

### ISSUE THREAD

**Issue by jazminorozco** [denali-design/denali-css#61]
Most of the toggles can't be toggled.

![Screen Shot 2020-04-19 at 2 37 15 PM](https://user-images.githubusercontent.com/20936130/79701046-d7ee4c80-824e-11ea-8fb8-b0e516174a77.png)

![Screen Shot 2020-04-19 at 2 36 59 PM](https://user-images.githubusercontent.com/20936130/79701051-e2104b00-824e-11ea-9213-11d063dc6091.png)

![Screen Shot 2020-04-19 at 2 37 08 PM](https://user-images.githubusercontent.com/20936130/79701056-e8062c00-824e-11ea-84b3-547def369109.png)

![Screen Shot 2020-04-19 at 2 36 40 PM](https://user-images.githubusercontent.com/20936130/79701242-5697b980-8250-11ea-9446-4ffdbb3758b3.png)

**Comment by chasturansky** [comment]
This is implemented this way.
