### ISSUE TITLE
Search Icon not aligned on navbar

### ISSUE THREAD

**Issue by ope-nz** [denali-design/denali-css#86]
Noticed this on the new release, the search icon is not aligned on the navbar.

![image](https://user-images.githubusercontent.com/26259049/80860110-bb73fa80-8cb9-11ea-8119-3f27a40da6ea.png)

You can see an example on the docs; https://denali.design/docs/2/components/navbar

**Comment by ope-nz** [comment]
Actually, looks like the construction of the nav section changed. Following the CSS demos (https://denali-design.github.io/denali-css/docs/#navbar) the search input appears correct.

![image](https://user-images.githubusercontent.com/26259049/80909059-449e3680-8d79-11ea-9f64-db004e9e8c44.png)

So I think its just a matter of updating the docs; https://denali.design/docs/2/components/navbar

**Comment by chasturansky** [comment]
Hi, 

Thank you for reporting. We noticed this issue in the documentation. It seems like the issue is when we are using the iframes to generate the examples. 

I will mark this as a duplicate. If you want to track progress. https://github.com/denali-design/denali-css/issues/59
